@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDcwNDY1NDR9.IGcAddTpTv4GJzde4swbNXtUaornchoNgdbQ4TL8Clo

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Test name",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "david@test.com",
  "password": "password"
}

### Groups index
GET http://localhost:3000/groups
Authorization: Bearer {{jwt}}


### Groups show
GET http://localhost:3000/groups/1
Authorization: Bearer {{jwt}}

### Nominations create
POST http://localhost:3000/nominations
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"name": "Texas Chainsaw Massacre",
"event_id": 1
}

### Votes create
POST http://localhost:3000/votes
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"user_id": 6,
"nomination_id": 8
}