### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Test name",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}